// <auto-generated />
using Harbour.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harbour.Migrations
{
    [DbContext(typeof(HarbourDbContext))]
    partial class HarbourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Harbour.Domain.ContainerTypeSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalDimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternalDimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SelfWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("VolumeM3")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContainerTypeSpecs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Contenedor seco 20 pies",
                            ExternalDimensions = "20x8x8.6 feet",
                            InternalDimensions = "19.4x7.7x7.9 feet",
                            IsActive = true,
                            MaxCapacity = 21700m,
                            Name = "DryVan20",
                            SelfWeight = 2330m,
                            VolumeM3 = 33.2m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Contenedor seco 40 pies",
                            ExternalDimensions = "40x8x8.6 feet",
                            InternalDimensions = "39.5x7.7x7.9 feet",
                            IsActive = true,
                            MaxCapacity = 26730m,
                            Name = "DryVan40",
                            SelfWeight = 3750m,
                            VolumeM3 = 67.7m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contenedor de altura alta 40 pies",
                            ExternalDimensions = "40x8x9.6 feet",
                            InternalDimensions = "39.5x7.7x8.9 feet",
                            IsActive = true,
                            MaxCapacity = 26500m,
                            Name = "HighCube40",
                            SelfWeight = 3970m,
                            VolumeM3 = 76.3m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Contenedor de altura alta 45 pies",
                            ExternalDimensions = "45x8x9.6 feet",
                            InternalDimensions = "44.6x7.7x8.9 feet",
                            IsActive = true,
                            MaxCapacity = 28350m,
                            Name = "HighCube45",
                            SelfWeight = 4850m,
                            VolumeM3 = 86.0m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Contenedor refrigerado 20 pies",
                            ExternalDimensions = "20x8x8.6 feet",
                            InternalDimensions = "18.3x7.2x7.6 feet",
                            IsActive = true,
                            MaxCapacity = 20800m,
                            Name = "Reefer20",
                            SelfWeight = 2900m,
                            VolumeM3 = 28.3m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Contenedor refrigerado 40 pies",
                            ExternalDimensions = "40x8x8.6 feet",
                            InternalDimensions = "37.6x7.2x7.6 feet",
                            IsActive = true,
                            MaxCapacity = 20350m,
                            Name = "Reefer40",
                            SelfWeight = 4650m,
                            VolumeM3 = 58.0m
                        });
                });

            modelBuilder.Entity("Harbour.Domain.PalletTypeSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SelfWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PalletTypeSpecs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pallet americano estándar",
                            Dimensions = "40x48 inches",
                            IsActive = true,
                            MaxCapacity = 1200m,
                            Name = "American",
                            SelfWeight = 28m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pallet europeo estándar",
                            Dimensions = "80x120 cm",
                            IsActive = true,
                            MaxCapacity = 1500m,
                            Name = "European",
                            SelfWeight = 25m
                        });
                });

            modelBuilder.Entity("Harbour.Domain.Ship", b =>
                {
                    b.Property<string>("ShipId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MaxCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinCapacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("SpotShip")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ShipId");

                    b.ToTable("Ships", (string)null);
                });

            modelBuilder.Entity("Harbour.Domain.StorageItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContainerId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PalletId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SelfWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ShipId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StorageItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("PalletId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ShipId");

                    b.HasIndex("StatusId");

                    b.ToTable("StorageItems", (string)null);

                    b.HasDiscriminator<string>("StorageItemType").HasValue("StorageItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Harbour.Domain.StorageStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StorageStatusTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elemento recibido en almacén",
                            IsActive = true,
                            Name = "Received"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Elemento cargado en vehículo/contenedor",
                            IsActive = true,
                            Name = "Loaded"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Elemento enviado/despachado",
                            IsActive = true,
                            Name = "Shipped"
                        });
                });

            modelBuilder.Entity("Harbour.Domain.Box", b =>
                {
                    b.HasBaseType("Harbour.Domain.StorageItem");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue("Box");
                });

            modelBuilder.Entity("Harbour.Domain.Container", b =>
                {
                    b.HasBaseType("Harbour.Domain.StorageItem");

                    b.Property<int>("ContainerTypeSpecId")
                        .HasColumnType("int");

                    b.HasIndex("ContainerTypeSpecId");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("Harbour.Domain.Pallet", b =>
                {
                    b.HasBaseType("Harbour.Domain.StorageItem");

                    b.Property<int>("PalletTypeSpecId")
                        .HasColumnType("int");

                    b.HasIndex("PalletTypeSpecId");

                    b.HasDiscriminator().HasValue("Pallet");
                });

            modelBuilder.Entity("Harbour.Domain.StorageItem", b =>
                {
                    b.HasOne("Harbour.Domain.Container", null)
                        .WithMany("Contents")
                        .HasForeignKey("ContainerId");

                    b.HasOne("Harbour.Domain.Pallet", null)
                        .WithMany("Contents")
                        .HasForeignKey("PalletId");

                    b.HasOne("Harbour.Domain.StorageItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Harbour.Domain.Ship", null)
                        .WithMany("Cargo")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Harbour.Domain.StorageStatusType", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Harbour.Domain.Container", b =>
                {
                    b.HasOne("Harbour.Domain.ContainerTypeSpec", "ContainerTypeSpec")
                        .WithMany()
                        .HasForeignKey("ContainerTypeSpecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContainerTypeSpec");
                });

            modelBuilder.Entity("Harbour.Domain.Pallet", b =>
                {
                    b.HasOne("Harbour.Domain.PalletTypeSpec", "PalletTypeSpec")
                        .WithMany()
                        .HasForeignKey("PalletTypeSpecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PalletTypeSpec");
                });

            modelBuilder.Entity("Harbour.Domain.Ship", b =>
                {
                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("Harbour.Domain.Container", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Harbour.Domain.Pallet", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
